version: '1.0'
services:
  database:
    image: postgis/postgis:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - ./init-database:/docker-entrypoint-initdb.d
      - postgres:/var/lib/postgresql/data
    networks:
      backend:
        aliases:
          - "database"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
  adminer:
    image: adminer
    ports:
      - 8070:8080
    networks:
      - backend
  driverservice:
    image: driver-service:latest
    ports:
      - "8080:8080"
    environment:
      PROFILE: "dev"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - backend
  rideservice:
    image: ride-service:latest
    ports:
      - "8083:8083"
    environment:
      PROFILE: "dev"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - backend


  passengerservice:
    image: passenger-service:latest
    ports:
      - "8081:8081"
    environment:
      PROFILE: "dev"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - backend

networks:
  backend:
    driver: bridge
volumes:
  postgres: