spring:
  kafka:
    consumer:
      auto-offset-reset: earliest
      group-id: driver-service-group
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

eureka:
  client:
    enabled: false

default:
  kafka:
    confirm-rating-receive-topic-name: driver_confirm_rating_receive
    consume-rating-topic-name: rate_driver_topic


