spring:
  datasource:
    url: jdbc:postgresql://database:5432/ride_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
  jooq:
    sql-dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      bootstrap-servers: kafka:9092
      client-id: ride-service

default:
  search-radius: 500
  min-radius: 200
  max-radius: 1000
  kafka:
    send-rating-to-driver-topic-name: rate_driver_topic
    send-rating-to-passenger-topic-name: rate_passenger_topic