spring:
  datasource:
    url: jdbc:postgresql://database:5432/ride_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
  jooq:
    sql-dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      bootstrap-servers: kafka:9092
      client-id: ride-service
    consumer:
      group-id: ride-service-group
  cloud:
    openfeign:
      client:
        config:
          driver-service:
            connect-timeout: 1000
            read-timeout: 1000
          passenger-service:
            connect-timeout: 1000
            read-timeout: 1000
default:
  search-radius: 500
  min-radius: 200
  max-radius: 1000
  kafka:
    send-rating-to-driver-topic-name: rate_driver_topic
    send-rating-to-passenger-topic-name: rate_passenger_topic
    confirm-driver-rating-receive-topic-name: driver_confirm_rating_receive
    confirm-passenger-rating-receive-topic-name: passenger_confirm_rating_receive
eureka:
  client:
    service-url:
      defaultZone: http://eurekaserver:8761/eureka/
  instance:
    prefer-ip-address: true


logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    org.springframework.transaction.interceptor: DEBUG
    com.zaxxer.hikari.pool: DEBUG
    org.hibernate: DEBUG
    org.apache.kafka.common.utils.AppInfoParser: DEBUG
    org.springframework.kafka: DEBUG


management:
  endpoints:
    web:
      exposure:
        include: prometheus, health
  metrics:
    tags:
      application: ${spring.application.name}