spring:
  datasource:
    url: jdbc:postgresql://database:5432/passenger_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
  h2:
    console:
      enabled: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      bootstrap-servers: kafka:9092
    producer:
      bootstrap-servers: kafka:9092


eureka:
  client:
    service-url:
      defaultZone: http://eurekaserver:8761/eureka/

message:
  source:
    basenames: "classpath:messages/api-error-response"

default:
  kafka:
    confirm-rating-receive-topic-name: passenger_confirm_rating_receive
    consume-rating-topic-name: rate_passenger_topic
