spring:
  datasource:
    url: jdbc:postgresql://database:5432/passenger_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
  h2:
    console:
      enabled: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml