spring:
  datasource:
    url: jdbc:postgresql://database:5432/passenger_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
  h2:
    console:
      enabled: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      bootstrap-servers: kafka:9092
    producer:
      bootstrap-servers: kafka:9092

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8070/auth/realms/modsen-realm
          jwk-set-uri: http://keycloak:8080/auth/realms/modsen-realm/protocol/openid-connect/certs
eureka:
  client:
    service-url:
      defaultZone: http://eurekaserver:8761/eureka/
  instance:
    hostname: PASSENGER-SERVICE
    prefer-ip-address: true

message:
  source:
    basenames: "classpath:messages/api-error-response"

default:
  kafka:
    confirm-rating-receive-topic-name: passenger_confirm_rating_receive
    consume-rating-topic-name: rate_passenger_topic

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health
  metrics:
    tags:
      application: ${spring.application.name}
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  tracing:
    enabled: true
    sampling:
      probability: 1

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    org.springframework.security: DEBUG